api_url: ws://localhost:8000/
use_local_api: true
ntfy_topic: my-transit-alerts
arrival_threshold_minutes: 5
check_interval_seconds: 30
subscriptions:
- feed: st
  route: st:40_100240
  stop: st:1_8494
  label: Hardware Stop (st:40_100240)
- feed: st
  route: st:1_100039
  stop: st:1_11920
  label: Hardware Stop (st:1_100039)
