name: PR newspaper
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  newspaper:
    permissions:
      contents: read
      pull-requests: read
    uses: tommyroar/pr-newspaper/.github/workflows/validate.yml@main
